name: Daily SEO Update
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install requests

      - name: Run SEO Script
        run: python index-ping.py

      - name: Commit and Push changes
        run: |
          git config --global user.name 'SEO-Bot'
          git config --global user.email 'bot@brightlane.io'
          git add .
          git commit -m "Daily Update" || echo "No changes"
          git push
